### ISSUE TITLE
Window phone 8.1 support?

### ISSUE THREAD

**Issue by MrGru** [qiankanglai/ImagePicker#3]
I don't see "App.xaml.cs (Win8.1 phone version only)"  in this repo? 
Does it support window phone 8.1?
In ImagePickerImpl.cpp I found only code: openPicker->PickSingleFileAndContinue(); when I test on my phone (8.1), it opened album image for selecting image file but nothing returned when I picked an image.

**Comment by qiankanglai** [comment]
I'm sorry this repo doesn't have the newest files.
You can find them in the pull request (though I don't think it will be merged :smile: )
https://github.com/cocos2d/cocos2d-x/pull/11344/files#diff-c3d75ef5195c6fd5c0a3cb33031546aaL12

I've only tested in the simulator
