### ISSUE TITLE
compile errors with Xcode

### ISSUE THREAD

**Issue by daqiuqu** [qiankanglai/ImagePicker#5]
I got 10 errors totaly, just like these:

cocos/scripting/js-bindings/auto/jsb_cocos2dx_extension_ImagePicker.cpp:43:53: No member named 'get' in 'mozilla::Maybe<JS::PersistentRooted<JSObject *> >'
cocos/scripting/js-bindings/auto/jsb_cocos2dx_extension_ImagePicker.cpp:186:18: No viable overloaded '='

**Comment by daqiuqu** [comment]
I just worked it out and submit a pull request, it works for me, thanks for your help!

**Comment by qiankanglai** [comment]
Merged, Thanks!
Maybe new JSB versions have changed API a little..
