### ISSUE TITLE
JSB for Cocos2d-x v3.11.1

### ISSUE THREAD

**Issue by Zinitter** [qiankanglai/ImagePicker#7]
@qiankanglai 

I can't use the current JSB file with v3.11.1 and would like to regenerate the JSB but not sure how to do it.

I know you have change to Unity3D, but can show me how you generate the JSB or share the file you generate the JSB?

Thank you.

**Comment by qiankanglai** [comment]
I remember I used the tool from cocos to bind JSB automatically, but modified it later by hand...

**Comment by Zinitter** [comment]
@qiankanglai 

Thanks for your reply.

There is a tool from Cocos - bindings-generator to generate the JSB/

The environment setup is ok as i tried the test folder for JSB within the bindings-generator folder.
But i don't know how to modify the file for Image Picker.

**Comment by qiankanglai** [comment]
I just modified it to have `class` to contain result, so I don't know how to describe. You may diff mine version with the generated one

I'll take time writing a simple tutorial if I have this weekend

**Comment by Zinitter** [comment]
@qiankanglai 

Thank you for your guide.

Are you modifying `framework/tools/tojs/cocos2dx_extension.ini` to include the ImagePicker?
I try edit the file to add in `ImagePicker` into the class.

# what classes to produce code for. You can use regular expressions here. When testing the regular
# expression, it will be enclosed in "^$", like this: "^Menu*$".
classes = AssetsManagerEx Manifest EventListenerAssetsManagerEx EventAssetsManagerEx Control.* ControlButton.* ScrollView$ TableView$ TableViewCell$ ImagePicker

Then add to `#include "ImagePicker/ImagePicker.h"` to `framework/extensions/cocos-ext.h` for header path.

Then run the `genbindings.py` and it success generate the binding.

However, i check the `extension.hpp` file,
I found there is ImagePicker binding but no ImagePickerDelegate binding.

What do i miss?

Thank you.

**Comment by Zinitter** [comment]
@qiankanglai 

I have success modified your code to work with Cocos2d-JS v3.11.1.

Thank you for your guide.

**Comment by uiopwang** [comment]
@Zinitter Can you send a pr to update this.I also need JSB for Cocos2d-x v3.11.1.Thx.

**Comment by qiankanglai** [comment]
@uiopwang Please refer to https://github.com/cocos2d/cocos2d-x/pull/11344
